# Generated by Django 3.0.5 on 2020-08-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
