# Generated by Django 3.0.5 on 2020-08-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
